<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>SntpUpdate</AssemblyTitle>
    <Product>SntpUpdate</Product>
    <Copyright>Copyright ©  2012</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Acn\LXProtocols.Acn.csproj" />
  </ItemGroup>
</Project>